export type IndustrySector =
  | "trades"
  | "health"
  | "tech"
  | "business"
  | "public"
  | "creative"
  | "logistics"
  | "education";

export type Industry = {
  id: string;
  name: string;
  sector: IndustrySector;
  blurb: string;
  topics: string[];
  safetyFirst?: boolean;
  aosAffinity: string[]; // skill ids that pair well
};

export const SECTORS: { id: IndustrySector; label: string }[] = [
  { id: "trades", label: "Trades & Field" },
  { id: "health", label: "Health & Safety" },
  { id: "tech", label: "Technology" },
  { id: "business", label: "Business & Ops" },
  { id: "public", label: "Public & Civic" },
  { id: "creative", label: "Creative" },
  { id: "logistics", label: "Logistics & Energy" },
  { id: "education", label: "Education" },
];

export const INDUSTRIES: Industry[] = [
  {
    id: "electrical",
    name: "Electrical",
    sector: "trades",
    blurb: "Wiring, power needs, and staying safe on the job.",
    topics: [
      "Electrical safety rules",
      "How much power is needed",
      "Safety outlets and breakers",
      "Wire protection tubes",
      "Finding electrical faults",
    ],
    safetyFirst: true,
    aosAffinity: ["evidence-gate", "construction-oversight", "permit-coordinator", "4-agent-orchestration"],
  },
  {
    id: "plumbing",
    name: "Plumbing",
    sector: "trades",
    blurb: "Clean water in, dirty water out, fixtures, and finding leaks.",
    topics: [
      "Drain and vent pipes",
      "Clean water supply",
      "Sinks toilets and fixtures",
      "Which safety rules apply",
      "Finding leaks",
    ],
    safetyFirst: true,
    aosAffinity: ["evidence-gate", "construction-oversight", "jurisdiction-ops"],
  },
  {
    id: "hvac",
    name: "HVAC / R",
    sector: "trades",
    blurb: "Heating, cooling, airflow, and safe equipment service.",
    topics: [
      "How cooling moves heat",
      "Temperature health checks",
      "Airflow",
      "Refrigerant license basics",
      "Heat pumps",
    ],
    safetyFirst: true,
    aosAffinity: ["evidence-gate", "construction-oversight", "4-agent-orchestration"],
  },
  {
    id: "welding",
    name: "Welding & Fabrication",
    sector: "trades",
    blurb: "Joining metal safely and checking that the weld is solid.",
    topics: [
      "Stick welding",
      "Wire-feed welding",
      "Preparing the joint",
      "Weld recipes",
      "Inspection",
    ],
    safetyFirst: true,
    aosAffinity: ["evidence-gate", "construction-oversight"],
  },
  {
    id: "construction",
    name: "Construction Management",
    sector: "trades",
    blurb: "Planning the job, asking clear plan questions, and coordinating the site.",
    topics: [
      "Planning the next few days",
      "Questions when plans are unclear",
      "Official job changes",
      "Safety plans",
      "Finishing and handing over",
    ],
    safetyFirst: true,
    aosAffinity: ["construction-oversight", "permit-coordinator", "public-records-forensics", "working-doc-manager"],
  },
  {
    id: "carpentry",
    name: "Carpentry & Framing",
    sector: "trades",
    blurb: "Framing, marking where things go, and finishing to a clear standard.",
    topics: [
      "Marking where things go",
      "How weight travels down",
      "Stairs",
      "Final ground height",
      "Nails screws and bolts",
    ],
    safetyFirst: true,
    aosAffinity: ["construction-oversight", "evidence-gate"],
  },
  {
    id: "nursing",
    name: "Nursing",
    sector: "health",
    blurb: "Patient care thinking, clear handoffs, and safety.",
    topics: [
      "Patient assessment",
      "Medicine safety",
      "Clear handoffs",
      "What to do first",
      "What your role allows",
    ],
    safetyFirst: true,
    aosAffinity: ["evidence-gate", "4-agent-orchestration", "shatter-protocol"],
  },
  {
    id: "emt",
    name: "EMT / EMS",
    sector: "health",
    blurb: "First response: scene safety, patient checks, and clear handoffs.",
    topics: [
      "Making the scene safe",
      "First patient check",
      "Step-by-step protocols",
      "Writing it down",
      "Handing off to the next team",
    ],
    safetyFirst: true,
    aosAffinity: ["evidence-gate", "4-agent-orchestration"],
  },
  {
    id: "pharmacy",
    name: "Pharmacy",
    sector: "health",
    blurb: "Safe medicine doses, interactions, and double-checks.",
    topics: [
      "Dose calculations",
      "Drug interactions",
      "Talking with patients",
      "Error traps",
      "Approved drug list",
    ],
    safetyFirst: true,
    aosAffinity: ["evidence-gate", "shatter-protocol"],
  },
  {
    id: "software",
    name: "Software Engineering",
    sector: "tech",
    blurb: "Building software carefully: design, fix, test, and review.",
    topics: [
      "System design",
      "Finding and fixing bugs",
      "Testing",
      "How programs connect",
      "Code review",
    ],
    aosAffinity: ["4-agent-orchestration", "reasoning-architect", "anti-pattern-scanner", "working-doc-manager"],
  },
  {
    id: "cybersecurity",
    name: "Cybersecurity",
    sector: "tech",
    blurb: "Protecting computer systems and practicing safe habits.",
    topics: [
      "Knowing what can go wrong",
      "Building safer systems",
      "Keeping simple logs",
      "What to do when something breaks",
      "Who can access what",
    ],
    aosAffinity: ["evidence-gate", "ops-hardening-architect", "report-operator", "shatter-protocol"],
  },
  {
    id: "it-support",
    name: "IT Support",
    sector: "tech",
    blurb: "Sorting tech problems, fixing carefully, and knowing when to escalate.",
    topics: [
      "Sorting problems by urgency",
      "How networks connect",
      "Proving who a user is",
      "Writing clear help tickets",
      "When to escalate",
    ],
    aosAffinity: ["evidence-gate", "4-agent-orchestration", "working-doc-manager"],
  },
  {
    id: "data",
    name: "Data & Analytics",
    sector: "tech",
    blurb: "Honest numbers, careful analysis, and clear reports.",
    topics: [
      "Choosing good metrics",
      "Query thinking",
      "Bias checks",
      "Dashboards",
      "Telling a story with numbers",
    ],
    aosAffinity: ["evidence-gate", "anti-pattern-scanner", "report-operator"],
  },
  {
    id: "cnc",
    name: "CNC & Manufacturing",
    sector: "trades",
    blurb: "Machine setup, precise cuts, and quality checks.",
    topics: [
      "Holding the workpiece",
      "How tight the tolerance is",
      "Choosing tools",
      "Machine code basics",
      "Quality checks",
    ],
    safetyFirst: true,
    aosAffinity: ["evidence-gate", "construction-oversight"],
  },
  {
    id: "quality",
    name: "Quality Assurance",
    sector: "business",
    blurb: "Standards, finding out-of-spec work, and fixing root causes.",
    topics: [
      "Quality control plans",
      "When work is out of standard",
      "Fixing problems at the root",
      "Audits",
      "Tracking where a part came from",
    ],
    aosAffinity: ["evidence-gate", "working-doc-manager", "report-operator"],
  },
  {
    id: "accounting",
    name: "Accounting",
    sector: "business",
    blurb: "Keeping books clean, checking numbers, and financial basics.",
    topics: [
      "Journal entries",
      "Matching the accounts",
      "Financial controls",
      "Statements",
      "Tax basics",
    ],
    aosAffinity: ["evidence-gate", "public-records-forensics"],
  },
  {
    id: "sales",
    name: "Sales",
    sector: "business",
    blurb: "Honest sales: listening, answering concerns, and fair deals.",
    topics: [
      "Learning the customer need",
      "Checking for a real fit",
      "Handling objections",
      "Writing proposals",
      "Keeping clean customer records",
    ],
    aosAffinity: ["content-ops", "evenhandedness-illusion-breaker"],
  },
  {
    id: "project-management",
    name: "Project Management",
    sector: "business",
    blurb: "Running a project: scope, risks, people, and delivery.",
    topics: [
      "What is in scope",
      "Risk list",
      "People involved",
      "The work that drives the finish date",
      "After-action review",
    ],
    aosAffinity: ["4-agent-orchestration", "working-doc-manager", "mission-spine-guard"],
  },
  {
    id: "culinary",
    name: "Culinary",
    sector: "creative",
    blurb: "Cooking skills, prep, food safety, and service.",
    topics: ["Knife skills", "Sauces", "Food safety", "Station setup", "Food costing"],
    safetyFirst: true,
    aosAffinity: ["evidence-gate", "working-doc-manager"],
  },
  {
    id: "hospitality",
    name: "Hospitality",
    sector: "business",
    blurb: "Guest care, shift operations, and service standards.",
    topics: [
      "Fixing a bad guest experience",
      "Written service steps",
      "Leading a shift",
      "Honest upselling",
      "Safety",
    ],
    aosAffinity: ["content-ops", "working-doc-manager"],
  },
  {
    id: "law-enforcement",
    name: "Law Enforcement",
    sector: "public",
    blurb: "Clear reports, professional judgment, and ethics education.",
    topics: [
      "Report writing",
      "Professional standards",
      "Handling evidence carefully",
      "Community contact",
      "Ethics",
    ],
    safetyFirst: true,
    aosAffinity: ["evidence-gate", "shatter-protocol", "public-records-forensics", "report-operator"],
  },
  {
    id: "teaching",
    name: "Teaching",
    sector: "education",
    blurb: "Planning lessons, checking learning, and running a classroom.",
    topics: [
      "Learning goals",
      "Step-by-step teaching",
      "Checking learning along the way",
      "Meeting different learners",
      "Feedback",
    ],
    aosAffinity: ["4-agent-orchestration", "content-systems-architect", "working-doc-manager"],
  },
  {
    id: "cdl",
    name: "CDL / Trucking",
    sector: "logistics",
    blurb: "Safe trucking: inspections, hours rules, cargo, and weather calls.",
    topics: [
      "Pre-trip inspection",
      "Hours-of-service rules",
      "Securing cargo",
      "Backing safely",
      "Weather decisions",
    ],
    safetyFirst: true,
    aosAffinity: ["evidence-gate", "jurisdiction-ops"],
  },
  {
    id: "aviation",
    name: "Aviation",
    sector: "logistics",
    blurb: "Aircraft systems, checklists, and careful flight decisions.",
    topics: [
      "Aircraft systems",
      "Checklists",
      "Weather",
      "Careful decision-making",
      "Human factors",
    ],
    safetyFirst: true,
    aosAffinity: ["evidence-gate", "4-agent-orchestration", "shatter-protocol"],
  },
  {
    id: "design",
    name: "Design",
    sector: "creative",
    blurb: "Visual design craft, layout, and useful feedback.",
    topics: [
      "What the eye sees first",
      "Typography",
      "Layout",
      "Giving useful critique",
      "Design systems",
    ],
    aosAffinity: ["visual-systems-architect", "content-systems-architect"],
  },
  {
    id: "video",
    name: "Video Production",
    sector: "creative",
    blurb: "Planning shots, capturing light and sound, and editing a story.",
    topics: ["Shot list", "Lighting", "Audio", "Edit structure", "Exporting the final file"],
    aosAffinity: ["content-ops", "visual-systems-architect"],
  },
  {
    id: "energy",
    name: "Energy & Utilities",
    sector: "logistics",
    blurb: "Power systems, lockout safety, and field work.",
    topics: [
      "Power generation",
      "Power distribution",
      "Lockout safety",
      "Keeping systems reliable",
      "Field safety",
    ],
    safetyFirst: true,
    aosAffinity: ["evidence-gate", "jurisdiction-ops", "construction-oversight"],
  },
  {
    id: "agriculture",
    name: "Agriculture",
    sector: "logistics",
    blurb: "Growing crops: soil, water, pests, and equipment choices.",
    topics: ["Soil health", "Irrigation", "Pest management", "Equipment", "Markets"],
    aosAffinity: ["evidence-gate", "jurisdiction-ops"],
  },
  {
    id: "automotive",
    name: "Automotive",
    sector: "trades",
    blurb: "Finding car problems carefully and repairing them right.",
    topics: [
      "How to diagnose",
      "Vehicle electrical",
      "Brakes",
      "Engine management",
      "Writing the service story",
    ],
    safetyFirst: true,
    aosAffinity: ["evidence-gate", "4-agent-orchestration"],
  },
  {
    id: "logistics",
    name: "Logistics",
    sector: "logistics",
    blurb: "Moving goods: inventory, routes, warehouses, and exceptions.",
    topics: [
      "Inventory",
      "Routing",
      "Service promises",
      "Warehousing",
      "Handling exceptions",
    ],
    aosAffinity: ["4-agent-orchestration", "working-doc-manager"],
  },
  {
    id: "civic-intelligence",
    name: "Public Information Literacy",
    sector: "public",
    blurb: "Reading original documents carefully and separating facts from guesses.",
    topics: [
      "Primary sources",
      "How approvals work (general)",
      "Simple checklists for claims",
      "Who can decide (public roles)",
      "Labeling facts vs guesses",
    ],
    aosAffinity: [
      "civic-intelligence-coordinator",
      "public-records-forensics",
      "permit-coordinator",
      "influence-mapping-analyst",
      "oversight-kit-builder",
      "evidence-gate",
      "sovereign-lens",
    ],
  },
  {
    id: "media-literacy",
    name: "Media Literacy & Narrative Analysis",
    sector: "public",
    blurb: "Reading news and claims carefully without getting spun.",
    topics: [
      "Source quality",
      "How a story is angled",
      "What is left out",
      "Emotional pressure",
      "Checking claims",
    ],
    aosAffinity: ["psyop-narrative-detector", "evidence-gate", "shatter-protocol", "sovereign-lens"],
  },
];

export function getIndustry(id: string) {
  return INDUSTRIES.find((i) => i.id === id);
}
