/**
 * Fedslop enemies — the South Park narrative sludge Pepe & Apu dismantle.
 * Satirical meme archetypes, not real people.
 */

export type EnemyId =
  | "slop_gremlin"
  | "talking_point_bot"
  | "midwit_manager"
  | "agenda_priest"
  | "fact_checker_in_name_only"
  | "grant_goblin"
  | "timeline_editor"
  | "arch_slop";

export type EnemyDef = {
  id: EnemyId;
  name: string;
  title: string;
  blurb: string;
  maxHp: number;
  attack: number;
  armor: number;
  cope: number;
  /** XP / gold on defeat */
  xp: number;
  gold: number;
  color: string;
  face: string;
  lines: string[];
  isBoss?: boolean;
};

export const ENEMIES: Record<EnemyId, EnemyDef> = {
  slop_gremlin: {
    id: "slop_gremlin",
    name: "Slop Gremlin",
    title: "Entry-level Fedslop",
    blurb: "Spams vibes. Allergic to footnotes.",
    maxHp: 40,
    attack: 8,
    armor: 2,
    cope: 1,
    xp: 18,
    gold: 12,
    color: "#a3a3a3",
    face: "🦠",
    lines: ["Trust the narrative!", "Source: dude trust me"],
  },
  talking_point_bot: {
    id: "talking_point_bot",
    name: "Talking-Point Bot",
    title: "Autogenerated outrage",
    blurb: "Runs on recycled press releases.",
    maxHp: 55,
    attack: 11,
    armor: 4,
    cope: 2,
    xp: 26,
    gold: 18,
    color: "#94a3b8",
    face: "🤖",
    lines: ["According to experts…", "This is settled science (citation needed)"],
  },
  midwit_manager: {
    id: "midwit_manager",
    name: "Midwit Manager",
    title: "PowerPoint warlord",
    blurb: "Confuses consensus with truth.",
    maxHp: 70,
    attack: 13,
    armor: 6,
    cope: 3,
    xp: 34,
    gold: 24,
    color: "#fbbf24",
    face: "📊",
    lines: ["Let's circle back.", "That's not the approved framing."],
  },
  agenda_priest: {
    id: "agenda_priest",
    name: "Agenda Priest",
    title: "High cleric of The Message",
    blurb: "Sermons in place of evidence.",
    maxHp: 85,
    attack: 15,
    armor: 7,
    cope: 4,
    xp: 42,
    gold: 30,
    color: "#c084fc",
    face: "⛪",
    lines: ["Heresy detected.", "Repent and retweet."],
  },
  fact_checker_in_name_only: {
    id: "fact_checker_in_name_only",
    name: "Fact-Checker (In Name Only)",
    title: "Label merchant",
    blurb: "Rates true things 'missing context' for sport.",
    maxHp: 95,
    attack: 16,
    armor: 8,
    cope: 5,
    xp: 50,
    gold: 36,
    color: "#38bdf8",
    face: "✅",
    lines: ["Rated: Misleading.", "We fact-checked the vibe."],
  },
  grant_goblin: {
    id: "grant_goblin",
    name: "Grant Goblin",
    title: "NGO loot goblin",
    blurb: "Eats budgets. Excretes white papers.",
    maxHp: 110,
    attack: 14,
    armor: 10,
    cope: 4,
    xp: 55,
    gold: 48,
    color: "#34d399",
    face: "💰",
    lines: ["This study was funded by… nevermind.", "Impact metrics go brrr."],
  },
  timeline_editor: {
    id: "timeline_editor",
    name: "Timeline Editor",
    title: "Memory-holer",
    blurb: "Edits yesterday so today makes sense.",
    maxHp: 130,
    attack: 18,
    armor: 9,
    cope: 6,
    xp: 70,
    gold: 55,
    color: "#f472b6",
    face: "✂️",
    lines: ["That never happened.", "You are misremembering on purpose."],
  },
  arch_slop: {
    id: "arch_slop",
    name: "ARCH-SLOP",
    title: "Final Form of the Fedslop Narrative",
    blurb:
      "The South Park storyline as nutrient paste: every joke sanded down, every truth outsourced, every citizen a NPC. Pepe and Apu are here to shred it.",
    maxHp: 280,
    attack: 22,
    armor: 14,
    cope: 10,
    xp: 200,
    gold: 150,
    color: "#ef4444",
    face: "🏛️",
    isBoss: true,
    lines: [
      "THE NARRATIVE IS INEVITABLE.",
      "CONSUME THE SLOP. QUESTION NOTHING.",
      "TRUTH TELLERS WILL BE… contextualized.",
    ],
  },
};

export type EnemyRuntime = {
  defId: EnemyId;
  name: string;
  hp: number;
  maxHp: number;
  attack: number;
  armor: number;
  cope: number;
  face: string;
  color: string;
  isBoss?: boolean;
};

export function spawnEnemy(id: EnemyId, scale = 1): EnemyRuntime {
  const d = ENEMIES[id];
  return {
    defId: id,
    name: d.name,
    hp: Math.round(d.maxHp * scale),
    maxHp: Math.round(d.maxHp * scale),
    attack: Math.round(d.attack * scale),
    armor: Math.round(d.armor * scale),
    cope: d.cope,
    face: d.face,
    color: d.color,
    isBoss: d.isBoss,
  };
}

/** Pick enemy by quest difficulty / chapter */
export function enemyForDifficulty(
  difficulty: number,
  chapter: number,
  isBossFight: boolean,
): EnemyId {
  if (isBossFight) return "arch_slop";
  const tier = Math.min(6, Math.max(0, difficulty + Math.floor(chapter / 2) - 1));
  const table: EnemyId[] = [
    "slop_gremlin",
    "talking_point_bot",
    "midwit_manager",
    "agenda_priest",
    "fact_checker_in_name_only",
    "grant_goblin",
    "timeline_editor",
  ];
  return table[tier] ?? "slop_gremlin";
}
