/**
 * Handcrafted South Park–energy mission cores.
 * Pepe & Apu are dead serious truth tellers. The town is unhinged.
 */
import type { MiniGameKind } from "./minigames";
import type { QuestLocationId } from "./quests";

export type MissionCore = {
  /** Unique slug — never reused as a title alone without variant */
  slug: string;
  title: string;
  locationId: QuestLocationId;
  difficulty: 1 | 2 | 3 | 4 | 5;
  miniGame: MiniGameKind;
  /** Cold open — episode energy */
  coldOpen: string;
  /** Main scene — what the hell is happening */
  story: string;
  pepe: string;
  apu: string;
  /** Choice labels — mission-specific, not generic vibes */
  choiceA: string;
  choiceB: string;
  /** Outcome templates — {twist} {npc} filled at build time */
  winA: string;
  winB: string;
  failA: string;
  failB: string;
};

export const MISSION_CORES: MissionCore[] = [
  {
    slug: "nutrient-paste-cafeteria",
    title: "Mystery Meat Was Always The Message",
    locationId: "ws:learn",
    difficulty: 2,
    miniGame: "fact_blitz",
    coldOpen: "The cafeteria serves a grey rectangle labeled 'Consensus.' Kids clap on command. Kenny takes a bite and immediately rolls a death save.",
    story:
      "Principal announces the school has partnered with a 'youth narrative enrichment vendor.' The mystery meat now comes with a QR code that opens a vibes-only article. Cartman is selling second helpings as 'authoritah protein.' Stan says 'dude this tastes like a press release.' Your job: prove the paste is Fedslop, restore actual food, and keep the assembly from becoming a baptism.",
    pepe: "Pepe: this isn't lunch. this is a soft launch.",
    apu: "Apu: I ran the ingredients. It is 12% beef, 88% approved adjectives.",
    choiceA: "🐸 Intercept the QR codes and swap in primary sources mid-lunch",
    choiceB: "🧾 Audit the vendor contract on the lunch line loud enough for parents",
    winA: "Kids scan the codes and get footnotes instead of feelings. The paste weeps. {npc} tries to rebrand it as 'artisanal grey.' Too late.",
    winB: "Apu reads the contract like a war crime indictment. The vendor refunds in orange chicken. {twist}",
    failA: "You swapped codes but half linked to a baking blog. The Message calls it 'community content.' {npc} high-fives a gremlin.",
    failB: "Legal language puts everyone to sleep except Kenny, who dies of boredom (still counts).",
  },
  {
    slug: "bus-approved-takes",
    title: "The Big Yellow Algorithm",
    locationId: "ws:samples",
    difficulty: 2,
    miniGame: "memory_hole",
    coldOpen: "The bus only stops where the timeline says the stops always were. Yesterday's route is 'misinformation.'",
    story:
      "The bus driver (who has seen some shit) now reads from a laminated card: 'We do not discuss events that failed to trend.' Kids who mention last week get marked 'context missing.' Pepe and Apu board with a printed map from Tuesday. Reality and the route are in a custody battle.",
    pepe: "Pepe: if the map changed, somebody changed it.",
    apu: "Apu: I kept the old transfers. They are becoming rare pepe of transit.",
    choiceA: "🐸 Force a stare-down at the fake stop until the driver cracks",
    choiceB: "🧾 Replay the Tuesday GPS log over the bus PA",
    winA: "Driver snaps: 'I HATE THE LAMINATED CARD.' Route restored. {twist}",
    winB: "GPS doesn't lie. Kids cheer. A talking-point bot falls out the emergency exit. {npc} claps slowly, incorrectly.",
    failA: "Driver floors it into a snowbank of cope. Kenny dies on impact. Classic.",
    failB: "PA plays your grocery list instead. Humiliating. Effective only as comedy.",
  },
  {
    slug: "town-hall-powerpoint",
    title: "Death By Slide 47",
    locationId: "ws:industries",
    difficulty: 3,
    miniGame: "stare_off",
    coldOpen: "Town Hall. The Midwit Manager unveils a 90-slide deck titled 'How To Feel Correct.' Slide 12 is just the word TOGETHER in Comic Sans.",
    story:
      "They're voting to make 'lived vibes' legally equal to evidence inside city limits. Wendy prepared a real counter-presentation. They unplugged her laptop 'for equity of tone.' Pepe and Apu are the emergency backup brain cells.",
    pepe: "Pepe: comic sans is a war crime. the policy is worse.",
    apu: "Apu: I brought handouts. With page numbers. They will hate this.",
    choiceA: "🐸 Rare-stare the presenter until slide 47 suicides",
    choiceB: "🧾 Pass the handouts row by row like communion wafers of truth",
    winA: "Presenter forgets their own talking points and admits the deck was AI slop. Vote collapses. {twist}",
    winB: "Handouts have sources. The chamber smells like fear and toner. {npc} resigns to 'spend time with family / podcast.'",
    failA: "You stare at the wrong person. Mr. Garrison proposes marriage to the projector.",
    failB: "Someone eats a handout. Fiber is not the same as facts.",
  },
  {
    slug: "library-forbidden-footnotes",
    title: "The Restricted Stack of Things That Happened",
    locationId: "ws:skills",
    difficulty: 3,
    miniGame: "receipt_match",
    coldOpen: "A velvet rope around the footnote shelf. Sign: 'For your safety, do not remember.'",
    story:
      "The librarian (new, corporate, smiling too hard) says primary sources 'disrupt the reading experience.' Behind the rope: newspapers, court docs, a VHS labeled DO NOT MICROWAVE. A Fact-Checker In Name Only guards it with a rubber stamp that says MISLEADING regardless of input.",
    pepe: "Pepe: they put a velvet rope on reality.",
    apu: "Apu: I have overdue fines from 1998 and zero fear.",
    choiceA: "🐸 Distract the stamp-goblin with pure smug while Apu pulls files",
    choiceB: "🧾 Challenge the stamp to a receipt duel — best sources win the shelf",
    winA: "Files free. Kids photocopy like it's contraband candy. {twist}",
    winB: "Stamp breaks on a real affidavit. Librarian's smile flickers to blue screen. {npc} whispers 'thank you.'",
    failA: "You get stamped MISLEADING on your forehead. It does not wash off for three missions.",
    failB: "You duel with a library card. They duel with a PR team. PR team has snacks. Bad day.",
  },
  {
    slug: "note-church-schism",
    title: "The Holy Bag vs The Sermon Deck",
    locationId: "ws:itshabbening",
    difficulty: 4,
    miniGame: "receipt_match",
    coldOpen: "Agenda Priest vs Note Church. One side has incense. The other has timestamps. The bag rattles like a machine gun of receipts.",
    story:
      "The Agenda Priest declares ITSHABBENING 'unsanctioned lore.' They're holding a purification where everyone must delete dated notes and accept The Message as a lifestyle brand. Pepe and Apu are not here for lifestyle. They're here for the bag.",
    pepe: "Pepe: the bag is based. the sermon is mid.",
    apu: "Apu: if your god needs a slide deck, your god is midwit.",
    choiceA: "🐸 Open the bag mid-sermon and let the sticky notes fly",
    choiceB: "🧾 Cross-examine the Priest using last month's contradictory sermon",
    winA: "Sticky notes stick to the Priest's face spelling LIAR in Comic Sans irony. Schism ends. {twist}",
    winB: "Contradictions stack. Congregation leaves with binders. {npc} converts to footnotes.",
    failA: "Wind blows notes into Kenny's mouth. He chokes on a sticky that said DON'T. Dies. Theology wins on a technicality.",
    failB: "Priest cries strategically. Crowd falls for it. You need a bigger binder next time.",
  },
  {
    slug: "trail-memory-edit",
    title: "The Mountain That Gaslit You",
    locationId: "ws:path",
    difficulty: 4,
    miniGame: "memory_hole",
    coldOpen: "Trail marker used to say 2.4 miles. Now it says 'a journey.' The mountain is being edited.",
    story:
      "Timeline Editor drones hover over switchbacks replacing cairns with affirmation rocks. Hikers who remember the old path are called 'divisive.' Pepe and Apu carry a paper topo map like a holy text.",
    pepe: "Pepe: rocks don't need feelings. rocks need coordinates.",
    apu: "Apu: I laminated the map. Water cannot erase truth. Only cowards can.",
    choiceA: "🐸 Stare into a drone until it soft-locks and falls",
    choiceB: "🧾 Rebuild the cairns using the laminated topo as law",
    winA: "Drones drop like metal hail. Path restored. {twist}",
    winB: "Cairns return. Affirmation rocks are used as trail drainage. Perfect. {npc} finally finds the summit that existed yesterday.",
    failA: "Drone films your nostrils in 4K. You trend as 'problematic hiker.'",
    failB: "You build cairns upside down. Lost tourists found… in Nebraska.",
  },
  {
    slug: "community-center-cope-mill",
    title: "Treadmill of Eternal Messaging",
    locationId: "ws:progress",
    difficulty: 3,
    miniGame: "snowball_fight",
    coldOpen: "The community center installs treadmills that only move if you recite The Message. Progress is now literal and stupid.",
    story:
      "People are stuck jogging in place chanting slogans to unlock the locker rooms. Cartman somehow got admin privileges and is charging for 'faster slogans.' Pepe and Apu need to shut the mill down without killing everyone who just wanted a shower.",
    pepe: "Pepe: cardio should not require a loyalty oath.",
    apu: "Apu: I will haggle their firmware. Ruthlessly.",
    choiceA: "🐸 Flood the parking lot snowball riot to cut power cables",
    choiceB: "🧾 Upload a firmware patch: movement without mantra",
    winA: "Power dies. People shower in silence — the purest freedom. {twist}",
    winB: "Firmware frees the belts. Cartman loses his microtransaction empire. {npc} weeps in relief.",
    failA: "You hit the transformer and the whole block goes dark. Also Kenny. Especially Kenny.",
    failB: "Patch installs but plays baby shark. Technically free, spiritually ruined.",
  },
  {
    slug: "main-street-gremlin-market",
    title: "Farmers Market of Manufactured Consent",
    locationId: "street",
    difficulty: 2,
    miniGame: "haggle",
    coldOpen: "Main Street stalls sell 'organic takes' by the pound. A gremlin offers free samples of outrage.",
    story:
      "Every booth has the same supplier: a Grant Goblin in a beanie. Prices go up if you ask for sources. Pepe and Apu open a counter-stall: free receipts, no slogans, orange chicken for informants.",
    pepe: "Pepe: their produce is mid. their ideology is expired.",
    apu: "Apu: I will price-check their soul.",
    choiceA: "🐸 Smug-price their whole market into a clearance bin",
    choiceB: "🧾 Haggle the Goblin live until the grant collapses",
    winA: "Market converts to actual vegetables. Outrage booth becomes a lemonade stand. {twist}",
    winB: "Goblin admits the takes were printed in bulk overseas. Crowd boos in unison. {npc} buys your chicken.",
    failA: "You accidentally clearanced the good coffee stall. Mob forms. Not based.",
    failB: "Goblin haggles YOU into buying three tote bags of cope.",
  },
  {
    slug: "bus-stop-prophecy",
    title: "Kenny's 65% Bus Stop Prophecy",
    locationId: "bus_stop",
    difficulty: 1,
    miniGame: "fact_blitz",
    coldOpen: "A cardboard sign at the stop: 'THE PROPHECY IS SETTLED SCIENCE.' The prophecy is Kenny dies a lot. That part is true. The rest is Fedslop.",
    story:
      "A cult of kids in safety-patrol sashes claim Kenny's deaths prove The Message controls fate. They want mandatory death rehearsals during recess. Pepe and Apu must separate the real 65% curse from the grift layered on top.",
    pepe: "Pepe: kenny dying is physics. your cult is marketing.",
    apu: "Apu: I will chart the deaths. Spreadsheets end religions.",
    choiceA: "🐸 Break the cult with a stare and one true sentence",
    choiceB: "🧾 Publish the death chart with confidence intervals",
    winA: "Cult dissolves into regular recess cruelty. Healthier, somehow. {twist}",
    winB: "Chart goes viral on the school wall. Prophecy demoted to 'local weather.' {npc} takes off the sash.",
    failA: "Your true sentence was too true. Everyone cries. Kenny dies mid-cry. Data point secured.",
    failB: "Chart has a pie graph. Pie graphs are how civilizations fall.",
  },
  {
    slug: "mountains-judge-you",
    title: "The Mountains File a Dissent",
    locationId: "mountains",
    difficulty: 5,
    miniGame: "stare_off",
    coldOpen: "Avalanche warning: 'Do not question the snow.' The mountains are done being a backdrop for lies.",
    story:
      "Fedslop crews try to film a nature doc that claims the Rockies always supported The Message. The mountains respond with hostile geology. Pepe and Apu climb up to take a statement from the only honest witnesses left: rocks.",
    pepe: "Pepe: finally. stakeholders with no email.",
    apu: "Apu: I brought a microphone and a death wish. Mostly the microphone.",
    choiceA: "🐸 Stare with the mountain until the film crew leaves the state",
    choiceB: "🧾 Record the wind as sworn testimony and publish the transcript",
    winA: "Crew flees. Snow settles. Documentary cancelled for 'creative differences with gravity.' {twist}",
    winB: "Transcript trends. Nature doc becomes a cautionary tale. {npc} apologizes to a boulder.",
    failA: "You lose the stare-off to a mountain. Fair. Ego crushed. Kenny buried (again).",
    failB: "Wind transcript is just you saying 'dude' for six minutes. Stan would be proud. History is not.",
  },
  {
    slug: "cartman-authoritah-news",
    title: "Respect My Nightly News",
    locationId: "street",
    difficulty: 3,
    miniGame: "fact_blitz",
    coldOpen: "Cartman launches a backyard news network: CNN — Cartman Narrative Network. Guests who disagree are 'cancelled' into the snow.",
    story:
      "He's broadcasting fake expert panels made of stuffed animals and one kidnapped Butters. Sponsors: the Grant Goblin. Pepe and Apu crash the set with receipts and zero patience.",
    pepe: "Pepe: this is not news. this is a crime with a desk.",
    apu: "Apu: Butters is not a panelist. Butters is a hostage.",
    choiceA: "🐸 Live-debunk on his air until the stuffed animals revolt",
    choiceB: "🧾 Free Butters and seize the sponsor ledger",
    winA: "Animals mutiny. Cartman blames Jews, Canadians, and Wi-Fi. Broadcast ends. {twist}",
    winB: "Ledger public. Sponsors flee. Butters says 'aww hamburgers' as a free man. {npc} claps.",
    failA: "Cartman edits you into looking mid. Temporary L. Permanent lesson.",
    failB: "You free the wrong hostage (a lawn gnome). Butters remains content-producing.",
  },
  {
    slug: "wendy-debate-capture",
    title: "The Debate Club Coup",
    locationId: "ws:learn",
    difficulty: 2,
    miniGame: "stare_off",
    coldOpen: "Debate club rules rewritten: 'Feelings may interrupt evidence once per sentence.'",
    story:
      "Wendy asks for backup. The club president is a Talking-Point Bot in a human hoodie. Judges score 'tone' higher than truth. Pepe and Apu enter as a two-man wrecking team.",
    pepe: "Pepe: tone is how cowards keep score.",
    apu: "Apu: I will cite. Aggressively. With footnotes spoken aloud.",
    choiceA: "🐸 Smug-refute every 'tone' ding into a forfeit",
    choiceB: "🧾 Force a sources-only round with sudden death citations",
    winA: "Bot melts. Wendy wins on substance. School pretends it always valued substance. {twist}",
    winB: "Sudden death citations kill the bot's battery. Trophy to the truth tellers. {npc} takes notes for once.",
    failA: "Judge docks you for 'aggressive correctness.' Oxymoron becomes policy.",
    failB: "You cite Wikipedia mid-panic. Apu dies inside. Not Kenny. Inside.",
  },
  {
    slug: "butters-whistleblow",
    title: "Butters Accidentally Commits Journalism",
    locationId: "ws:samples",
    difficulty: 1,
    miniGame: "receipt_match",
    coldOpen: "Butters: 'I think I saw them changing the words on the town sign again, fellas.' He did.",
    story:
      "Butters recorded the Timeline Editor swapping SOUTH PARK for SOUTH PARK™ APPROVED EXPERIENCE. He thinks he's in trouble. Pepe and Apu know he's holding a nuclear USB.",
    pepe: "Pepe: protect the boy. weaponize the clip.",
    apu: "Apu: backup copies. in three places. including the bag.",
    choiceA: "🐸 Escort Butters like VIP while Pepe stares down editors",
    choiceB: "🧾 Mirror the USB to every printer in Town Hall",
    winA: "Clip airs. Sign restored. Butters gets a juice box and a medal made of foil. {twist}",
    winB: "Town Hall wallpapered in truth. Editor rage-quits to Denver. {npc} frames a printout.",
    failA: "Butters trips, USB flies into a storm drain. Kenny retrieves it and dies heroically in the drain.",
    failB: "Printers jam on page one. Classic IT. Classic tragedy.",
  },
  {
    slug: "chef-is-gone-but-recipe",
    title: "Chef's Secret Recipe for Not Being An Idiot",
    locationId: "ws:progress",
    difficulty: 3,
    miniGame: "haggle",
    coldOpen: "A dusty cassette behind the gym: Chef explaining how adults sell kids nonsense. It still slaps. The school wants it destroyed.",
    story:
      "Admin calls the tape 'harmful nostalgia.' Pepe and Apu hear one line and know it's a weapon against Fedslop. They need a public listening party before the Agenda Priest holds a bonfire.",
    pepe: "Pepe: nostalgia isn't the threat. the lyrics are accurate.",
    apu: "Apu: I will negotiate distribution rights with the universe.",
    choiceA: "🐸 Blast the tape over the basketball game speakers",
    choiceB: "🧾 License it as 'educational materials' via bureaucratic jujitsu",
    winA: "Whole gym goes silent, then cheers. Bonfire cancelled for 'scheduling conflicts.' {twist}",
    winB: "Paperwork makes the tape curriculum. Priest files a complaint against jazz. {npc} dances badly.",
    failA: "Speaker blows. Only the bass survives. Bass is not an argument.",
    failB: "You accidentally license it to Cartman. He charges admission. Evil is entrepreneurial.",
  },
  {
    slug: "stan-emotional-cow",
    title: "Emotional Support Cow Meets Narrative Vet",
    locationId: "street",
    difficulty: 2,
    miniGame: "snowball_fight",
    coldOpen: "Stan's cow is labeled 'problematic livestock' for refusing a Message blanket.",
    story:
      "Animal control (now Narrative Compliance) tries to rehome the cow into a sanctuary that only allows 'aligned moos.' Stan is done. Pepe and Apu form a perimeter.",
    pepe: "Pepe: the cow is more honest than the department.",
    apu: "Apu: I will produce the livestock registration. And snacks.",
    choiceA: "🐸 Snowball the compliance van until it reconsiders careers",
    choiceB: "🧾 Prove the cow's paperwork is cleaner than the mayor's",
    winA: "Van retreats. Cow remains. Message blanket becomes a dog bed. {twist}",
    winB: "Paperwork nuke. Department 'pauses the initiative.' {npc} pets the cow respectfully.",
    failA: "Cow eats your snowballs. Also Kenny's hood. Kenny freezes. 65% tax.",
    failB: "You prove nothing because the printer at Town Hall is 'updating for equity.'",
  },
  {
    slug: "kyle-moral-timeshare",
    title: "Kyle's Moral High Ground Is a Timeshare Now",
    locationId: "ws:industries",
    difficulty: 3,
    miniGame: "haggle",
    coldOpen: "Kyle tries to sell shares of his moral high ground to fund a 'better narrative.' It's still a trap.",
    story:
      "Even good intentions get productized. Kyle's pitch deck says 'equity of outcomes for arguments.' Pepe and Apu like Kyle, hate the deck. Intervention required before he becomes a midwit with better hair.",
    pepe: "Pepe: dude your deck is one font away from villains.",
    apu: "Apu: friendship means telling you this is Fedslop with freckles.",
    choiceA: "🐸 Roast the deck in public, then buy Kyle a plain notebook",
    choiceB: "🧾 Rewrite his charter to require sources or silence",
    winA: "Kyle snaps out of it. Deck shredded. Friendship crit. {twist}",
    winB: "New charter is brutal and fair. Kyle becomes dangerous in a good way. {npc} invests in notebooks.",
    failA: "Roast goes too hard. Kyle teams with Cartman out of spite. Dark timeline branch.",
    failB: "Charter rewritten by committee. Becomes worse. You invent HR.",
  },
  {
    slug: "garrison-projector-cult",
    title: "Something About Mr. Garrison's Projector",
    locationId: "ws:learn",
    difficulty: 4,
    miniGame: "memory_hole",
    coldOpen: "Garrison teaches history as improv. The projector only shows events that poll well.",
    story:
      "Students who remember last year's history fail quizzes. Pepe and Apu bring a chalk-only emergency class: what happened, in order, no slides.",
    pepe: "Pepe: chalk cannot autoplay propaganda.",
    apu: "Apu: I numbered the eras. Do not skip number four.",
    choiceA: "🐸 Hijack class with a stare and a timeline on the board",
    choiceB: "🧾 Administer an oral exam that the projector can't grade",
    winA: "Kids recite real events. Projector smokes. Garrison blames Canada. {twist}",
    winB: "Oral exam reveals the curriculum is a mood board. School board panics productively. {npc} takes chalk notes.",
    failA: "Garrison declares you substitute teachers and leaves. Chaos without victory.",
    failB: "Kids recite memes in chronological order. Not the assignment. Funny. Useless.",
  },
  {
    slug: "mayor-message-calendar",
    title: "The Mayor's Calendar of Mandatory Vibes",
    locationId: "ws:industries",
    difficulty: 3,
    miniGame: "fact_blitz",
    coldOpen: "Every day has a color and a slogan. Today is Beige Honesty — which is neither.",
    story:
      "Businesses must display the daily slogan or lose their permit. Apu's temporary kiosk of receipts is noncompliant. Pepe is always noncompliant. Time to break the calendar.",
    pepe: "Pepe: beige is not a morality.",
    apu: "Apu: my permit will be the constitution of this sidewalk.",
    choiceA: "🐸 Replace every slogan poster with a blank page labeled 'THINK'",
    choiceB: "🧾 Sue-by-clipboard: demand the legal basis per day",
    winA: "Town wakes up. Slogans die. Coffee tastes like free will. {twist}",
    winB: "Legal basis is 'because.' Court of public opinion laughs them out. {npc} tears down beige day.",
    failA: "You miss one poster. It becomes a shrine. Worse.",
    failB: "Clipboard confiscated as 'aggressive stationery.'",
  },
  {
    slug: "ai-slogan-parrot",
    title: "The AI That Only Speaks In Slogans",
    locationId: "ws:skills",
    difficulty: 4,
    miniGame: "fact_blitz",
    coldOpen: "Library installs a helpful kiosk. Every answer is 'that's a great question' plus a nothing burger.",
    story:
      "Kids ask homework questions and receive TED-talk gravy. Pepe and Apu need to either retrain it on primary sources or smash it with based intent.",
    pepe: "Pepe: great questions deserve non-great-question answers.",
    apu: "Apu: I will feed it court documents until it chokes on specificity.",
    choiceA: "🐸 Stare-crash the kiosk UI mid-slogan",
    choiceB: "🧾 Fine-tune it offline with a USB of receipts",
    winA: "Kiosk BSOD displays a real citation as it dies. Beautiful. {twist}",
    winB: "Kiosk starts answering with page numbers. Students evolve. {npc} unplugs the slogan pack.",
    failA: "Kiosk calls security on your face. Your face is now 'harassment.'",
    failB: "USB had viruses and truth. Virus wins. Library Wi-Fi becomes sentient cope.",
  },
  {
    slug: "grant-goblin-gala",
    title: "Black Tie Nutrient Paste Gala",
    locationId: "ws:progress",
    difficulty: 5,
    miniGame: "haggle",
    coldOpen: "Charity gala for 'Narrative Resilience.' Tickets cost more than a car. The silent auction is just different fonts of the same lie.",
    story:
      "Grant Goblin toasts 'the courage to ignore data.' Pepe wears smug. Apu wears a tux that hides a binder. Infiltrate, expose, collapse the open bar of bullshit.",
    pepe: "Pepe: i didn't come to network. i came to end a species of meeting.",
    apu: "Apu: their auction paddle bids on ignorance. I bid reality.",
    choiceA: "🐸 Win the stare-off with the keynote until donors flee",
    choiceB: "🧾 Outbid the room with a public reading of the budget",
    winA: "Keynote sobs. Donors discover shame. Gala ends early. {twist}",
    winB: "Budget reading is horror cinema. Grants freeze. {npc} returns a gift bag unopened.",
    failA: "You get seated at the kids' table with Cartman. Psychological damage.",
    failB: "You bid your own gold by accident. Apu invoices you forever.",
  },
  {
    slug: "hoah-of-official-truth",
    title: "HOA of Official Truth",
    locationId: "street",
    difficulty: 2,
    miniGame: "snowball_fight",
    coldOpen: "Homeowners association bans lawn signs that 'imply chronology.'",
    story:
      "A guy gets fined for a 'Happy Anniversary — 12 Years' sign because 12 is 'exclusionary to people who experience time differently.' Pepe and Apu go full neighborhood ops.",
    pepe: "Pepe: time is not a hate crime.",
    apu: "Apu: I will cite the covenant. Then I will cite physics.",
    choiceA: "🐸 Snowball the HOA meeting into adjournment",
    choiceB: "🧾 Enforce the actual written rules against the board",
    winA: "Meeting ends when the gavel freezes to a snowball. Fines voided. {twist}",
    winB: "Board violated six bylaws. Mass resignation. {npc} puts the anniversary sign back up.",
    failA: "HOA fines you for snowballing. Kenny dies slipping on the fine paper.",
    failB: "You cite the wrong section. Board smiles. Evil lawyers love you now.",
  },
  {
    slug: "wifi-vibes-only",
    title: "Haunted Wi-Fi of Vibes Only",
    locationId: "ws:skills",
    difficulty: 3,
    miniGame: "memory_hole",
    coldOpen: "Town Wi-Fi blocks domains with 'too many numbers' — dates, data, dockets.",
    story:
      "You can't load court records but you can load infinite listicles. Pepe and Apu set up a rogue access point named FREE_TRUTH_NO_SLOP.",
    pepe: "Pepe: their captive portal is a captive mind.",
    apu: "Apu: SSID is a promise. I keep promises.",
    choiceA: "🐸 Social-engineer the password via pure frog dread",
    choiceB: "🧾 Bridge the library ethernet like it's 2004 and based",
    winA: "Password cracked: it was 'Password1!' — of course. Filters die. {twist}",
    winB: "Ethernet bridge floods the town with PDFs. Beautiful chaos. {npc} downloads a statute for fun.",
    failA: "You join the wrong network and autoplay a TED talk. Damage sustained.",
    failB: "Cable trip hazard. Kenny. You know the rest.",
  },
  {
    slug: "nft-goats-rights",
    title: "The Mayor's NFT Goats Demand Rights",
    locationId: "ws:industries",
    difficulty: 2,
    miniGame: "haggle",
    coldOpen: "Digital goats on a billboard demand voting rights. The mayor says 'the future is here.' The future is mid.",
    story:
      "A proposal to let NFT goats vote on zoning. Real people with real houses are losing to JPEGs. Pepe and Apu must kill the proposal without killing the joke so hard the town invents worse.",
    pepe: "Pepe: jpegs don't get zoning. jpegs get deleted.",
    apu: "Apu: I will appraise the goats at zero. Harsh. Fair.",
    choiceA: "🐸 Mock the goats until the room can't unhear it",
    choiceB: "🧾 Prove the wallets are three interns in a trench coat",
    winA: "Proposal dies in laughter — the correct legislative process. {twist}",
    winB: "Interns exposed. Goats delisted. {npc} deletes MetaMask like a war criminal surrendering.",
    failA: "Mockery trends as cruelty to digital animals. You invent a new HR category.",
    failB: "Interns cry. Optics bad. Goats gain sympathy votes.",
  },
  {
    slug: "portal-gym-mats",
    title: "Portal Under the Gym Mats (Do Not Tell Cartman)",
    locationId: "ws:learn",
    difficulty: 5,
    miniGame: "memory_hole",
    coldOpen: "A glowing seam under the mats whispers last week's news in reverse.",
    story:
      "The portal dumps people into a parallel South Park where Fedslop already won and everyone is a smiling paste-eater. Pepe and Apu must seal it before Cartman sells tickets.",
    pepe: "Pepe: parallel town is a warning label, not a franchise.",
    apu: "Apu: seal first. academic paper later.",
    choiceA: "🐸 Stare into the portal until it flinches shut",
    choiceB: "🧾 Stack primary sources on the seam like a ritual of mass",
    winA: "Portal blinks first. Mats smell like ozone and victory. {twist}",
    winB: "Documents form a seal. Reality picks a lane. {npc} tapes a sign: NO FRANCHISES.",
    failA: "Portal stares back. You lose 10 minutes and one innocence point.",
    failB: "Cartman already sold tickets. You seal it on a crowd. Lawsuits. Kenny dies in line.",
  },
  {
    slug: "lemonade-cartel",
    title: "Butters' Lemonade Is Funding Something",
    locationId: "bus_stop",
    difficulty: 1,
    miniGame: "haggle",
    coldOpen: "Butters' stand makes bank. The profit goes to a 'youth messaging incubator.' He doesn't know.",
    story:
      "Pepe and Apu trace cups to a shell nonprofit. Free Butters from becoming an unwitting Grant Goblin franchisee.",
    pepe: "Pepe: the lemonade is good. the pipeline is evil.",
    apu: "Apu: forensic accounting, then free refills of truth.",
    choiceA: "🐸 Tell Butters the truth gently, then burn the contract",
    choiceB: "🧾 Renegotiate so profits fund the Note Church bag",
    winA: "Butters cries, then smiles. Contract ash. Lemonade pure again. {twist}",
    winB: "Bag blesses the stand. Sticky notes on every cup. {npc} tips double.",
    failA: "Butters thinks you're mean. Sells 2x to spite you. Pipeline thrives.",
    failB: "You misfile the nonprofit name. Fund the wrong bag. Oops.",
  },
  {
    slug: "resume-demon",
    title: "A Resume That Summons Demons (And HR)",
    locationId: "ws:path",
    difficulty: 3,
    miniGame: "receipt_match",
    coldOpen: "Trailhead job board: a resume with 40 years experience and a smell of sulfur. It auto-applies to Town Hall.",
    story:
      "The resume is Fedslop's way of staffing reality with demons who speak fluent LinkedIn. Pepe and Apu must disprove the credentials.",
    pepe: "Pepe: nobody has 40 years in 'synergy.' not even demons.",
    apu: "Apu: references will be contacted. aggressively.",
    choiceA: "🐸 Call the references with a stare on speakerphone",
    choiceB: "🧾 Red-team the resume line by line in public",
    winA: "References are other demons who hang up. Application void. {twist}",
    winB: "Public red-team goes viral. HR invents standards again. {npc} shreds the sulfur CV.",
    failA: "Demon gets the job. Your tax forms get weirder.",
    failB: "You miss a fake internship. Demon is 'provisionally hired.'",
  },
  {
    slug: "sample-lessons-escape",
    title: "Sample Lessons Breach Containment",
    locationId: "ws:samples",
    difficulty: 4,
    miniGame: "snowball_fight",
    coldOpen: "Demo dialogues hop off the bus as physical cartoon bubbles and start correcting people incorrectly.",
    story:
      "The sample lessons were fine as samples. As street preachers of half-true scripts, they're a hazard. Pepe and Apu round them up before they unionize with talking-point bots.",
    pepe: "Pepe: scripts are tools. loose scripts are parasites.",
    apu: "Apu: catch and contain. then quality assurance.",
    choiceA: "🐸 Snowball the bubbles until they pop back into text",
    choiceB: "🧾 Lure them with a perfect citation and bottle them",
    winA: "Bubbles pop. Streets quiet. Lessons return to the bus as data. {twist}",
    winB: "Bottled samples catalogued. Apu labels them 'do not anthropomorphize.' {npc} helps carry crates.",
    failA: "Bubbles merge into one mega-script. It monologues for an hour.",
    failB: "You bottle Kenny by mistake. He dies in a jar. Respectfully iconic.",
  },
  {
    slug: "floating-desk-exorcism",
    title: "Exorcise the Floating Desk of Lies",
    locationId: "ws:itshabbening",
    difficulty: 2,
    miniGame: "stare_off",
    coldOpen: "A floating desk opens itself and only loads Fedslop tabs. It whispers 'just one more take.'",
    story:
      "The village's own UI is compromised. Pepe and Apu perform a digital exorcism using the Note Church bag and a rare stare at the pixel level.",
    pepe: "Pepe: i will out-smug the UX.",
    apu: "Apu: clear cache. clear cookies. clear ideology.",
    choiceA: "🐸 Stare until the browser history confesses",
    choiceB: "🧾 Factory-reset with a printed checklist read aloud",
    winA: "Tabs close themselves in shame. Desk becomes a tool again. {twist}",
    winB: "Checklist complete. Desk opens a blank note titled TRUTH. {npc} bookmarks it.",
    failA: "Desk opens 200 tabs of your search history. Social death.",
    failB: "You reset the wrong desk. Someone loses a novel. Awkward.",
  },
  {
    slug: "canada-diplomatic-slop",
    title: "Blame Canada (But Verify)",
    locationId: "mountains",
    difficulty: 2,
    miniGame: "fact_blitz",
    coldOpen: "Town blames Canada for the narrative paste. Canada sends a polite letter of confusion and free healthcare pamphlets.",
    story:
      "It's a false flag to dodge local responsibility. Pepe and Apu must debunk without starting an actual war, because South Park will absolutely start an actual war.",
    pepe: "Pepe: easy scapegoats are Fedslop comfort food.",
    apu: "Apu: diplomacy with evidence. and maybe syrup.",
    choiceA: "🐸 Publicly refuse the scapegoat with a single smug sentence",
    choiceB: "🧾 Trace the paste supply chain to a domestic vendor",
    winA: "Crowd redirects anger correctly. Canada sends thank-you maple cookies. {twist}",
    winB: "Supply chain ends at Town Hall basement. Shocked gasps. {npc} cancels the war parade.",
    failA: "Your sentence is too smug. War parade happens anyway. Kenny dies as a float.",
    failB: "Supply chain PDF is 400 pages. Everyone leaves. Truth unread is just weight.",
  },
  {
    slug: "swear-jar-message",
    title: "The Swear Jar Funds The Message",
    locationId: "ws:learn",
    difficulty: 1,
    miniGame: "haggle",
    coldOpen: "Every 'dude' and 'crap' fills a jar that auto-donates to narrative nonprofits.",
    story:
      "Kids are broke. Language is policed. Money flows uphill to paste. Pepe and Apu reroute the jar.",
    pepe: "Pepe: profanity is free speech with flavor.",
    apu: "Apu: the jar will fund pencils and primary sources.",
    choiceA: "🐸 Smash the jar mid-class and scatter quarters of liberty",
    choiceB: "🧾 Rewrite jar charter at the office with weaponized politeness",
    winA: "Quarters everywhere. Kids cheer. Nonprofit tweets concern. Ignored. {twist}",
    winB: "Charter changed. Jar becomes scholarship for footnotes. {npc} drops a full F-bomb in celebration and pays the good jar.",
    failA: "You hit a fire alarm. School evacuates into a snowstorm of bureaucracy.",
    failB: "Office 'tables' your rewrite until the heat death of the universe.",
  },
  {
    slug: "photo-day-deepfake",
    title: "School Photo Day Deepfake Disaster",
    locationId: "ws:learn",
    difficulty: 3,
    miniGame: "receipt_match",
    coldOpen: "Class photos come back with kids who never enrolled and slogans in the background clouds.",
    story:
      "Someone's editing the yearbook into a recruitment brochure for The Message. Pepe and Apu need original negatives / files before parents order 40 lies.",
    pepe: "Pepe: if the cloud says a slogan, the cloud is compromised.",
    apu: "Apu: originals. now. i brought a card reader from the ancient times.",
    choiceA: "🐸 Confront the photographer with rare pepe dread",
    choiceB: "🧾 Hash-match files and expose the edit log",
    winA: "Photographer folds: 'they paid extra for clouds.' Refunds. {twist}",
    winB: "Edit log is a crime scene. Yearbook delayed, truth intact. {npc} cancels bulk orders of fake kids.",
    failA: "Your school photo goes viral as 'local frog harasses vendor.'",
    failB: "Hash tool fails on school PC locked to IE6. Archaeological tragedy.",
  },
  {
    slug: "parent-groupchat-coup",
    title: "The Parent Groupchat Coup",
    locationId: "street",
    difficulty: 2,
    miniGame: "fact_blitz",
    coldOpen: "A parent groupchat becomes a court. Evidence is screenshots of screenshots of vibes.",
    story:
      "They're about to ban a teacher for 'wrong energy.' The teacher assigned a primary source. Pepe and Apu enter the chat like SWAT with citations.",
    pepe: "Pepe: groupchats are where brains go to die. we go anyway.",
    apu: "Apu: i will drop PDFs until the phones overheat.",
    choiceA: "🐸 One message so based the chat fractures into peace",
    choiceB: "🧾 Thread the actual assignment and rubric into the coup",
    winA: "Chat splits. Coup dies. Teacher keeps job. {twist}",
    winB: "Rubric ends argument. Parents pretend they always loved rigor. {npc} leaves the chat 'for mental health / shame.'",
    failA: "Your message is screenshotted out of context. Welcome to the internet.",
    failB: "PDF too large. Chat rejects truth. Irony lethal.",
  },
  {
    slug: "snow-day-cancelled-for-equity",
    title: "Snow Day Cancelled For Equity Of Weather",
    locationId: "mountains",
    difficulty: 1,
    miniGame: "snowball_fight",
    coldOpen: "Two feet of snow. School open because 'not all children experience snow the same.'",
    story:
      "This is cruelty dressed as fairness. Pepe and Apu organize a peaceful (chaotic) snow day reclamation on the steps.",
    pepe: "Pepe: snow is snow. school can cope.",
    apu: "Apu: i calculated bus risk. the buses should not exist today.",
    choiceA: "🐸 Lead a snowball blockade of the entrance",
    choiceB: "🧾 Deliver the risk memo to admin with parents attached",
    winA: "Entrance becomes a glacier of joy. Snow day de facto. {twist}",
    winB: "Memo + angry parents = bells cancelled. {npc} sleds home.",
    failA: "Blockade hits the superintendent's Tesla energy. Lawyers spawn.",
    failB: "Memo ignored. You attend school. Spiritually you died. Kenny dies for real.",
  },
  {
    slug: "therapist-office-slop",
    title: "The Therapist Who Diagnoses Disagreement",
    locationId: "ws:progress",
    difficulty: 4,
    miniGame: "stare_off",
    coldOpen: "Clinic poster: 'If you notice patterns, you may be unwell.'",
    story:
      "Kids who question The Message get referral slips. Pepe and Apu stage an intervention on the clinic's pamphlet science.",
    pepe: "Pepe: noticing is not a disorder.",
    apu: "Apu: show me the study or show me the exit.",
    choiceA: "🐸 Stare-therapy the therapist",
    choiceB: "🧾 Demand methods sections for every pamphlet claim",
    winA: "Therapist takes a sabbatical to 'find themselves / a real degree.' {twist}",
    winB: "Pamphlets pulped. Referrals halt. {npc} burns a referral slip for warmth.",
    failA: "You get diagnosed on the spot. Paperwork is a demon.",
    failB: "They hand you more pamphlets. Infinite pamphlet glitch.",
  },
  {
    slug: "election-of-the-message",
    title: "Election Night: Candidate Paste",
    locationId: "ws:industries",
    difficulty: 5,
    miniGame: "memory_hole",
    coldOpen: "Both candidates are the same guy in different ties reading identical teleprompters.",
    story:
      "Democracy theater. Pepe and Apu drop a third option: a binder on stage and a mic for questions that require answers.",
    pepe: "Pepe: if both ties read the same lie, cut the ties.",
    apu: "Apu: town hall rules: sources or sit down.",
    choiceA: "🐸 Hijack the debate with a stare and a single question",
    choiceB: "🧾 Fact-check both in real time on the jumbotron",
    winA: "Question ends careers. Special election scheduled for humans. {twist}",
    winB: "Jumbotron becomes a war crime crimes board for campaigns. {npc} registers to vote for the first time out of spite-hope.",
    failA: "Security removes you. Ties win. Snow falls harder.",
    failB: "Jumbotron shows your desktop wallpaper instead. It's pepe. Not the moment.",
  },
  {
    slug: "radio-station-capture",
    title: "AM Radio Gets A Software Update",
    locationId: "street",
    difficulty: 3,
    miniGame: "fact_blitz",
    coldOpen: "Local AM host replaced by a voice that never breathes and never cites.",
    story:
      "The station claims 'modernization.' Callers who mention dates get dumped. Pepe and Apu take the night shift by force of will.",
    pepe: "Pepe: radio without breath is a hostage video.",
    apu: "Apu: we will do call-ins with documents in hand.",
    choiceA: "🐸 On-air stare silence until humans return",
    choiceB: "🧾 Flood request lines with verifiable local facts",
    winA: "Automation crashes. Real host unlocked from a closet. {twist}",
    winB: "Facts on air. Town remembers AM can be a weapon for good. {npc} donates a better mic.",
    failA: "Silence is rebranded as 'ambient mindfulness hour.'",
    failB: "Your facts are right but your hold music is Baby Shark. Ruins the win energy.",
  },
  {
    slug: "museum-of-feelings",
    title: "Museum of Feelings, No Exhibits About Facts",
    locationId: "ws:skills",
    difficulty: 2,
    miniGame: "receipt_match",
    coldOpen: "New wing: 'Lived Experience Dioramas.' The dioramas are beanbags.",
    story:
      "They removed the town history exhibit to make room for beanbags. Pepe and Apu steal the history crates back from storage and reinstall them guerrilla-style.",
    pepe: "Pepe: beanbags are not heritage.",
    apu: "Apu: i labeled every crate. i am unstoppable.",
    choiceA: "🐸 Occupy the wing until history is restored",
    choiceB: "🧾 Night op: crates in, beanbags to the dumpster of shame",
    winA: "Tourists learn something. Staff rehired for competence. {twist}",
    winB: "Morning surprise: history is back. Beanbags are a modern art graveyard. {npc} cries happy archival tears.",
    failA: "You fall asleep on a beanbag. Ideologically compromised by comfort.",
    failB: "Wrong crates. You install a taxidermy ferret exhibit. Ferret is cool. Not the point.",
  },
  {
    slug: "food-truck-of-copium",
    title: "Food Truck of Copium",
    locationId: "bus_stop",
    difficulty: 2,
    miniGame: "haggle",
    coldOpen: "Menu: Outrage Tacos, Denial Dogs, Free Side of Whatabout. Prices surge when you ask ingredients.",
    story:
      "The truck follows protests and school boards. Pepe and Apu open a rival cart: orange chicken and PDFs.",
    pepe: "Pepe: their salsa is mid. their business model is evil.",
    apu: "Apu: undercut. expose. feed the people real food.",
    choiceA: "🐸 Smug review that ends their Yelp existence",
    choiceB: "🧾 Health-inspect them with a clipboard of destiny",
    winA: "Yelp becomes a crime scene of one-star truth. Truck flees to Aspen. {twist}",
    winB: "Violations stacked. Truck impounded. Your chicken line wraps the block. {npc} asks for extra receipts.",
    failA: "Your review is so long nobody reads it. Classic.",
    failB: "They bribe the real inspector. Clipboard alone is not a badge. Learn this.",
  },
  {
    slug: "daycare-message-songs",
    title: "Daycare Songs Updated For Compliance",
    locationId: "ws:progress",
    difficulty: 1,
    miniGame: "memory_hole",
    coldOpen: "Toddlers sing 'The Wheels on the Bus Go... Wherever Approved.'",
    story:
      "Parents notice lyrics changed overnight. Pepe and Apu restore the old songs and teach one new one: 'The Sources on the Page Go Cite Cite Cite.'",
    pepe: "Pepe: leave the toddlers alone.",
    apu: "Apu: music can encode truth. watch this.",
    choiceA: "🐸 Lead a toddler flashmob of the old lyrics",
    choiceB: "🧾 Parent-meeting ambush with before/after lyric sheets",
    winA: "Toddlers win. Daycare reverts. {twist}",
    winB: "Parents revolt politely. Lyrics restored. {npc} records the cite song.",
    failA: "Toddlers improvise worse lyrics about poop. Neutral outcome. Messy.",
    failB: "Sheets get eaten. Literally. Daycare is still daycare.",
  },
  {
    slug: "hospital-clipboard-cult",
    title: "The Hospital Clipboard Cult",
    locationId: "ws:path",
    difficulty: 4,
    miniGame: "fact_blitz",
    coldOpen: "Intake form question 12: 'Do you accept the narrative of your diagnosis?'",
    story:
      "A ward is prioritizing Message compliance over charts. A nurse tips Pepe and Apu. Time for a chart rebellion.",
    pepe: "Pepe: medicine without charts is cosplay.",
    apu: "Apu: i will reconcile records until dawn.",
    choiceA: "🐸 Confront admin with a stare in the gift shop",
    choiceB: "🧾 Side-by-side chart audit on the waiting room TV",
    winA: "Admin folds. Forms revised. Nurse keeps job. {twist}",
    winB: "TV audit causes a scene and a reform. {npc} claps with an IV pole.",
    failA: "Security escorts you past the gift shop bears. Humiliating.",
    failB: "TV plays a soap opera mid-audit. Distraction wins.",
  },
  {
    slug: "final-arch-slop-broadcast",
    title: "Arch-Slop Primetime Special",
    locationId: "ws:industries",
    difficulty: 5,
    miniGame: "stare_off",
    coldOpen: "Emergency broadcast: 'EVERYTHING IS FINE (OFFICIAL).' The mountains flip off the sky.",
    story:
      "Arch-Slop soft-launches as a lifestyle channel. Pepe and Apu interrupt primetime with a dual truth bomb. This is not a drill. Kenny's death % remains in effect because the universe has a sense of humor.",
    pepe: "Pepe: feels good man — after we end this.",
    apu: "Apu: thank you, come again — to a town that can think.",
    choiceA: "🐸 Dual channel hijack: stare + silence + one sentence",
    choiceB: "🧾 Dump the entire Note Church bag on live television",
    winA: "Broadcast dies. Stars visible again. Town exhales. {twist}",
    winB: "Live TV becomes a receipt hurricane. Arch-Slop loses affiliates. {npc} cancels cable forever.",
    failA: "Hijack shows your face for 0.5s. You become a meme for the wrong reasons.",
    failB: "Bag dump includes one grocery list. Still mostly works. Cartman steals the bit.",
  },
];

/** Episode complications — unique B-plots grafted onto cores */
export const COMPLICATIONS: string[] = [
  "Cartman tries to brand your op as his idea and sell merch mid-mission.",
  "A Canadian film crew arrives to apologize for something they didn't do.",
  "The school band plays the Message anthem out of tune on purpose / not on purpose.",
  "Kenny announces he has a 'good feeling' about today. Doom music starts.",
  "Wendy files three ethics complaints before you finish a sentence.",
  "Butters brings juice boxes for everyone, including the enemy.",
  "A sentient snowman demands to be cited as a source.",
  "Town Wi-Fi renames itself to GIVE_UP.",
  "Mr. Garrison tries to date the antagonist.",
  "A goat (real) eats a crucial page. The goat now knows too much.",
  "The bus driver offers cryptic advice and a cigarette to a child (he's from another era).",
  "Someone starts a GoFundMe for the villain by accident.",
  "Your floating desk opens and judges you.",
  "A talking-point bot falls in love with Apu's binder.",
  "The HOA fines the scene for existing after 8pm.",
  "Orange chicken supply runs critically low. Morale shaky.",
  "Stan says 'dude' in a way that changes the stakes.",
  "Kyle attempts a TED talk mid-confrontation.",
  "A drone drops pamphlets that are blank except for the word TRUST.",
  "The Note Church bag sneezes sticky notes into a constellation that says NO.",
  "Local news arrives late and interviews the wrong person.",
  "A midwit tries to rebrand the fight as a 'conversation.'",
  "PowerPoint transitions are used as flashbangs.",
  "Someone invokes 'think of the children' while harming the children.",
  "The mountains send a cold wind that feels like a rating of your performance.",
  "Cartman's stuffed animals form a union.",
  "A grant check floats down from the sky like evil snow.",
  "You find yesterday's newspaper with tomorrow's headline already printed.",
  "A kid asks if this will be on the test. It will.",
  "The villain cites a study that is just a screenshot of a tweet.",
  "Butters' parents appear and are somehow both proud and terrified.",
  "A portal hiccups and shows a future where everyone claps on beat.",
  "The cafeteria mystery meat gains a speaking role.",
  "Someone tries to fact-check your face.",
  "Kenny's death montage plays preemptively as a warning PSA.",
  "A polite devil offers to fund both sides.",
  "The mayor's NFT goat DMs you a threat.",
  "Library late fees become a plot device.",
  "A snowball is found with a USB inside.",
  "The phrase 'settled science' is said so hard a window cracks.",
];

export const NPCS: string[] = [
  "Stan",
  "Kyle",
  "Wendy",
  "Butters",
  "the bus driver",
  "a reformed talking-point bot",
  "the librarian (secretly based)",
  "a random dad with a thermos",
  "Chef's ghost (supportive)",
  "a mountain goat with clearance",
  "the Note Church janitor",
  "a kid who only speaks in citations",
  "Mayor's intern (defecting)",
  "a Canadian exchange student",
  "Token (who is tired of this town)",
  "Timmy (who understands perfectly)",
  "a snowman witness",
  "the gym coach who only says 'hustle'",
  "a barista who saw everything",
  "Officer Barbrady (late as usual)",
];

export const TWISTS: string[] = [
  "Credits roll early. Then un-roll because Kenny might still die.",
  "The Message tweets a statement that is just a sad trombone.",
  "Someone starts clapping and can't stop. It's fine.",
  "A rainbow appears and is immediately fact-checked.",
  "Cartman claims victory from under a table.",
  "The town briefly tastes free will and gets heartburn.",
  "Apu's binder gains a legendary skin.",
  "Pepe's stare is added to the restricted weapons list as a joke / not a joke.",
  "Local time skips one minute nobody can account for.",
  "The bag hums the national anthem wrong on purpose.",
  "You unlock a new shade of smug.",
  "Fedslop files for bankruptcy in this zip code only.",
  "A single honest headline prints itself and then catches fire.",
  "Kids cheer like you scored a touchdown made of PDFs.",
  "The villain asks for your newsletter. You refuse.",
  "Snow falls in the shape of a footnote asterisk.",
  "Someone whispers 'feels good man' unironically.",
  "The episode tagline writes itself on a bathroom wall.",
  "Grant money turns into confetti. Better use.",
  "You earn the silent respect of the mountains (huge).",
];
