/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as GetYoursRouteImport } from './routes/get-yours'
import { Route as PathRouteImport } from './routes/path'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as TutorRouteImport } from './routes/tutor'
import { Route as DemoIndexRouteImport } from './routes/demo.index'
import { Route as DemoIndustryIdRouteImport } from './routes/demo.$industryId'
import { Route as SkillsIndexRouteImport } from './routes/skills.index'
import { Route as SkillsSkillIdRouteImport } from './routes/skills.$skillId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const GetYoursRoute = GetYoursRouteImport.update({
  id: '/get-yours',
  path: '/get-yours',
  getParentRoute: () => rootRouteImport,
} as any)
const PathRoute = PathRouteImport.update({
  id: '/path',
  path: '/path',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorRoute = TutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRoute,
} as any)
const DemoIndustryIdRoute = DemoIndustryIdRouteImport.update({
  id: '/$industryId',
  path: '/$industryId',
  getParentRoute: () => DemoRoute,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SkillsRoute,
} as any)
const SkillsSkillIdRoute = SkillsSkillIdRouteImport.update({
  id: '/$skillId',
  path: '/$skillId',
  getParentRoute: () => SkillsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/explore': typeof ExploreRoute
  '/get-yours': typeof GetYoursRoute
  '/path': typeof PathRoute
  '/progress': typeof ProgressRoute
  '/skills': typeof SkillsRouteWithChildren
  '/tutor': typeof TutorRoute
  '/demo/$industryId': typeof DemoIndustryIdRoute
  '/skills/$skillId': typeof SkillsSkillIdRoute
  '/demo/': typeof DemoIndexRoute
  '/skills/': typeof SkillsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/get-yours': typeof GetYoursRoute
  '/path': typeof PathRoute
  '/progress': typeof ProgressRoute
  '/tutor': typeof TutorRoute
  '/demo/$industryId': typeof DemoIndustryIdRoute
  '/skills/$skillId': typeof SkillsSkillIdRoute
  '/demo': typeof DemoIndexRoute
  '/skills': typeof SkillsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/explore': typeof ExploreRoute
  '/get-yours': typeof GetYoursRoute
  '/path': typeof PathRoute
  '/progress': typeof ProgressRoute
  '/skills': typeof SkillsRouteWithChildren
  '/tutor': typeof TutorRoute
  '/demo/$industryId': typeof DemoIndustryIdRoute
  '/skills/$skillId': typeof SkillsSkillIdRoute
  '/demo/': typeof DemoIndexRoute
  '/skills/': typeof SkillsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/explore'
    | '/get-yours'
    | '/path'
    | '/progress'
    | '/skills'
    | '/tutor'
    | '/demo/$industryId'
    | '/skills/$skillId'
    | '/demo/'
    | '/skills/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/get-yours'
    | '/path'
    | '/progress'
    | '/tutor'
    | '/demo/$industryId'
    | '/skills/$skillId'
    | '/demo'
    | '/skills'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/explore'
    | '/get-yours'
    | '/path'
    | '/progress'
    | '/skills'
    | '/tutor'
    | '/demo/$industryId'
    | '/skills/$skillId'
    | '/demo/'
    | '/skills/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  GetYoursRoute: typeof GetYoursRoute
  PathRoute: typeof PathRoute
  ProgressRoute: typeof ProgressRoute
  SkillsRoute: typeof SkillsRouteWithChildren
  TutorRoute: typeof TutorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-yours': {
      id: '/get-yours'
      path: '/get-yours'
      fullPath: '/get-yours'
      preLoaderRoute: typeof GetYoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/path': {
      id: '/path'
      path: '/path'
      fullPath: '/path'
      preLoaderRoute: typeof PathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor': {
      id: '/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof TutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/$industryId': {
      id: '/demo/$industryId'
      path: '/$industryId'
      fullPath: '/demo/$industryId'
      preLoaderRoute: typeof DemoIndustryIdRouteImport
      parentRoute: typeof DemoRoute
    }
    '/skills/': {
      id: '/skills/'
      path: '/'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof SkillsRoute
    }
    '/skills/$skillId': {
      id: '/skills/$skillId'
      path: '/$skillId'
      fullPath: '/skills/$skillId'
      preLoaderRoute: typeof SkillsSkillIdRouteImport
      parentRoute: typeof SkillsRoute
    }
  }
}

interface DemoRouteChildren {
  DemoIndustryIdRoute: typeof DemoIndustryIdRoute
  DemoIndexRoute: typeof DemoIndexRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoIndustryIdRoute: DemoIndustryIdRoute,
  DemoIndexRoute: DemoIndexRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

interface SkillsRouteChildren {
  SkillsSkillIdRoute: typeof SkillsSkillIdRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
}

const SkillsRouteChildren: SkillsRouteChildren = {
  SkillsSkillIdRoute: SkillsSkillIdRoute,
  SkillsIndexRoute: SkillsIndexRoute,
}

const SkillsRouteWithChildren =
  SkillsRoute._addFileChildren(SkillsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRouteWithChildren,
  ExploreRoute: ExploreRoute,
  GetYoursRoute: GetYoursRoute,
  PathRoute: PathRoute,
  ProgressRoute: ProgressRoute,
  SkillsRoute: SkillsRouteWithChildren,
  TutorRoute: TutorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
